const fs   = require('fs');
const solc = require('solc');

const VIA_IR = true;              // 必须和 BscScan 一致
const OPTIMIZE = 200;

/* ── 读取源码 ── */
const simplePath = './contracts-simple/SimpleToken.sol';
const distPath   = './contracts-simple/DividendDistributor.sol';

const simpleSrc = fs.readFileSync(simplePath, 'utf8');
const distSrc   = fs.readFileSync(distPath,   'utf8');

/* ── 构建 standard-json 输入 ── */
const input = JSON.stringify({
  language: 'Solidity',
  sources: {
    'SimpleToken.sol':          { content: simpleSrc },
    'DividendDistributor.sol': { content: distSrc   }
  },
  settings: {
    viaIR: VIA_IR,
    optimizer: { enabled: true, runs: OPTIMIZE },
    outputSelection: { '*': { '*': ['abi','evm.bytecode','evm.deployedBytecode'] } }
  }
});

/* ── 编译 ── */
console.log('⚙️  编译中 (viaIR=' + VIA_IR + ', runs=' + OPTIMIZE + ')...');
const output = JSON.parse(solc.compile(input));

if (output.errors) {
  const errs = output.errors.filter(e => e.severity === 'error');
  if (errs.length) { console.error(JSON.stringify(errs, null, 2)); process.exit(1); }
  output.errors.forEach(e => console.warn('⚠️ ', e.formattedMessage || e.message));
}

/* ── 提取 SimpleToken ── */
const simple = output.contracts['SimpleToken.sol'].SimpleToken;
const abiST  = simple.abi;
const byteST = '0x' + simple.evm.bytecode.object;

/* ── 提取 DividendDistributor ── */
const dist = output.contracts['DividendDistributor.sol'].DividendDistributor;
const abiDI  = dist.abi;
const byteDI = '0x' + dist.evm.bytecode.object;

/* ── 写入 contract_data.js ── */
const jsST = `// Auto-generated by compile.js – DO NOT EDIT\nmodule.exports = {\n  ABI: ${JSON.stringify(abiST, null, 2)},\n  BYTECODE: \"${byteST}\"\n};\n`;
fs.writeFileSync('contract_data.js', jsST);
console.log('✅ contract_data.js 已更新');

/* ── 写入 distributor_data.js ── */
const jsDI = `// Auto-generated by compile.js – DO NOT EDIT\nmodule.exports = {\n  ABI: ${JSON.stringify(abiDI, null, 2)},\n  BYTECODE: \"${byteDI}\"\n};\n`;
fs.writeFileSync('distributor_data.js', jsDI);
console.log('✅ distributor_data.js 已更新');

/* ── 写入 standard-input.json（BscScan 验证用）── */
const standardInput = {
  language: 'Solidity',
  sources: {
    'SimpleToken.sol':          { content: simpleSrc },
    'DividendDistributor.sol': { content: distSrc }
  },
  settings: {
    viaIR: VIA_IR,
    optimizer: { enabled: true, runs: OPTIMIZE },
    outputSelection: { '*': { '*': ['abi','evm.bytecode','evm.deployedBytecode'] } }
  }
};
fs.writeFileSync('standard-input.json', JSON.stringify(standardInput, null, 2));
console.log('✅ standard-input.json 已更新（BscScan 验证用）');

console.log('\n🎉 全部完成！');
