const fs   = require('fs');
const solc = require('solc');

const VIA_IR   = true;
const OPTIMIZE = 200;

/* ── 读源码 ── */
const simplePath = './contracts-simple/SimpleToken.sol';
const distPath   = './contracts-simple/DividendDistributor.sol';
const simpleSrc  = fs.readFileSync(simplePath, 'utf8');
const distSrc    = fs.readFileSync(distPath,   'utf8');

/* ── 编译 SimpleToken (单文件) ── */
console.log('⚙️  编译 SimpleToken (viaIR=' + VIA_IR + ', runs=' + OPTIMIZE + ')...');
const stInput = JSON.stringify({
  language: 'Solidity',
  sources: { 'SimpleToken.sol': { content: simpleSrc } },
  settings: {
    viaIR: VIA_IR,
    optimizer: { enabled: true, runs: OPTIMIZE },
    evmVersion: 'london',
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'evm.bytecode.sourceMap',
      'evm.deployedBytecode.object', 'evm.deployedBytecode.sourceMap'], '': ['id'] } }
  }
});
const stOut = JSON.parse(solc.compile(stInput));
if (stOut.errors) {
  stOut.errors.filter(e => e.severity === 'error').forEach(e => { console.error(e.formattedMessage); process.exit(1); });
  stOut.errors.forEach(e => console.warn('⚠️ ', e.formattedMessage || e.message));
}
const st = stOut.contracts['SimpleToken.sol'].SimpleToken;
const abiST  = st.abi;
const byteST = '0x' + st.evm.bytecode.object;

// 写入 contract_data.js
fs.writeFileSync('contract_data.js',
  '// Auto-generated by compile.js — DO NOT EDIT\nvar CONTRACT_DATA = {\n  ABI: ' +
  JSON.stringify(abiST, null, 2) + ',\n  BYTECODE: \"' + byteST + '\"\n};\n');
console.log('✅ contract_data.js 已更新');

// 写入 standard-input.json（BscScan 验证 SimpleToken）
fs.writeFileSync('standard-input.json', JSON.stringify({
  language: 'Solidity',
  sources: { 'SimpleToken.sol': { content: simpleSrc } },
  settings: {
    viaIR: VIA_IR,
    optimizer: { enabled: true, runs: OPTIMIZE },
    evmVersion: 'london',
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'evm.bytecode.sourceMap',
      'evm.deployedBytecode.object', 'evm.deployedBytecode.sourceMap'], '': ['id'] } }
  }
}, null, 2));
console.log('✅ standard-input.json 已更新（BscScan SimpleToken 验证用）');

/* ── 编译 DividendDistributor (单文件) ── */
console.log('⚙️  编译 DividendDistributor...');
const diInput = JSON.stringify({
  language: 'Solidity',
  sources: { 'DividendDistributor.sol': { content: distSrc } },
  settings: {
    viaIR: VIA_IR,
    optimizer: { enabled: true, runs: OPTIMIZE },
    evmVersion: 'london',
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'], '': ['id'] } }
  }
});
const diOut = JSON.parse(solc.compile(diInput));
if (diOut.errors) {
  diOut.errors.filter(e => e.severity === 'error').forEach(e => { console.error(e.formattedMessage); process.exit(1); });
}
const di = diOut.contracts['DividendDistributor.sol'].DividendDistributor;
const byteDI = '0x' + di.evm.bytecode.object;

fs.writeFileSync('distributor_data.js',
  '// Auto-generated by compile.js — DO NOT EDIT\nvar DISTRIBUTOR_DATA = {\n  ABI: ' +
  JSON.stringify(di.abi, null, 2) + ',\n  BYTECODE: \"' + byteDI + '\"\n};\n');
console.log('✅ distributor_data.js 已更新');

// 写入 distributor-input.json（BscScan 验证用）
fs.writeFileSync('distributor-input.json', JSON.stringify({
  language: 'Solidity',
  sources: { 'DividendDistributor.sol': { content: distSrc } },
  settings: {
    viaIR: VIA_IR,
    optimizer: { enabled: true, runs: OPTIMIZE },
    evmVersion: 'london',
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'evm.bytecode.sourceMap',
      'evm.deployedBytecode.object', 'evm.deployedBytecode.sourceMap'], '': ['id'] } }
  }
}, null, 2));
console.log('✅ distributor-input.json 已更新（BscScan DividendDistributor 验证用）');

console.log('\n🎉 全部完成！');
